# Generated by Django 5.2.4 on 2025-08-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('mobile_banking', 'Mobile Banking')], max_length=50)),
                ('status', models.CharField(choices=[('escrow', 'Held by Admin'), ('released', 'Released to Seller'), ('refunded', 'Refunded to Buyer'), ('failed', 'Failed')], default='escrow', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
