# Generated by Django 5.2.4 on 2025-08-13 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('location', models.CharField(max_length=255)),
                ('owner_type', models.CharField(choices=[('rent', 'Rent'), ('sell', 'Sell')], max_length=50)),
                ('property_type', models.CharField(choices=[('house', 'House'), ('townhouse', 'Townhouse'), ('apartment', 'Apartment'), ('roomonly', 'Room Only'), ('bedonly', 'Bed Only')], max_length=50)),
                ('bedroom', models.IntegerField(blank=True, null=True)),
                ('bathroom', models.IntegerField(blank=True, null=True)),
                ('square', models.IntegerField(blank=True, null=True)),
                ('laundry_type', models.CharField(choices=[('in_until_laundry', 'In_until laundry'), ('laundry_in_building', 'Laundry in building'), ('laundry_available', 'Laundry available'), ('none', 'None')], default='none', max_length=50)),
                ('parking_type', models.CharField(choices=[('garage_parking', 'Garage Parking'), ('strest_parking', 'Street parking'), ('off_street_parking', 'Off street parking'), ('parking_available', 'Parking available'), ('none', 'None')], default='none', max_length=50)),
                ('air_conditioning_type', models.CharField(choices=[('central_ac', 'Central AC'), ('ac_available', 'AC available'), ('none', 'None')], max_length=50)),
                ('heating_type', models.CharField(choices=[('central_heating', 'Central heating'), ('electric_heating', 'Electric heating'), ('gas_heating', 'Gas heating'), ('radiator_heating', 'Radiator heating'), ('heating_available', 'Heating available'), ('none', 'None')], default='none', max_length=50)),
                ('user_id', models.IntegerField()),
                ('video', models.FileField(blank=True, null=True, upload_to='properties/videos/')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='property.property')),
            ],
        ),
    ]
